### PR TITLE
Add option to recenter pointer after jump

### PR DESCRIPTION
**Pull request by dakra**
Convert defvar to defcustom.

### CODE REVIEW

**Comment by proofit404** [comment]
Hi, thanks for the contribution! 

I'm interested in this PR. Can we refactor boolean option to the `djangonaut-navigate-line-hook` and set it to `'(recenter)` by default?

Regards, Artem.

**Comment by dakra** [comment]
Sure. I even thought about it as well as some people prefer `reposition-window` to `recenter` but the boolean version was just simpler to implement ;)
I'll update the PR

**Comment by dakra** [comment]
@proofit404 done

The elaborate comment is from `imenu-after-jump-hook` where
I got the idea from in case you're wondering ;)

**Comment by proofit404** [comment]
Cool!

**Pull request merged**
